name: Build + Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Notify Discord
        run: |
          echo "Sending to Discord..."
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"Deployment Complete!\"}" \
               "${{ secrets.WEBHOOK_PARTYPETE }}"
